openapi: 3.0.1
info:
  title: Note App Crud
  version: v1
servers:
  - url: http://localhost:8080
    description: Generated server url
tags:
  - name: user
    description: the User API
  - name: note
    description: the Note API
paths:
  /user/signup:
    post:
      tags:
        - user
      summary: Register User
      operationId: signup
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/SignRequest'
        required: true
      responses:
        '200':
          description: successful operation
          content:
            '*/*':
              schema:
                $ref: '#/components/schemas/ResponseSign'
        '401':
          description: failed operation
          content:
            '*/*':
              schema:
                $ref: '#/components/schemas/ResponseMessage'
  /user/login:
    post:
      tags:
        - user
      summary: Login User
      operationId: login
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/SignRequest'
        required: true
      responses:
        '200':
          description: successful operation
          content:
            '*/*':
              schema:
                $ref: '#/components/schemas/ResponseSign'
        '401':
          description: failed operation
          content:
            '*/*':
              schema:
                $ref: '#/components/schemas/ResponseMessage'
  /note:
    get:
      tags:
        - note
      summary: List of user notes
      operationId: listNote
      responses:
        '200':
          description: successful operation
          content:
            '*/*':
              schema:
                $ref: '#/components/schemas/ResponseListNoteResponse'
        '401':
          description: failed operation
          content:
            '*/*':
              schema:
                $ref: '#/components/schemas/ResponseMessage'
      security:
        - bearerAuth: []
    post:
      tags:
        - note
      summary: Add Note to User List
      operationId: addNote
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/NoteRequest'
        required: true
      responses:
        '200':
          description: successful operation
          content:
            '*/*':
              schema:
                $ref: '#/components/schemas/ResponseNoteResponse'
        '400':
          description: failed operation
          content:
            '*/*':
              schema:
                $ref: '#/components/schemas/ResponseMessage'
        '401':
          description: failed operation
          content:
            '*/*':
              schema:
                $ref: '#/components/schemas/ResponseMessage'
      security:
        - bearerAuth: []
  /note/{id}:
    get:
      tags:
        - note
      summary: Fetch User Note
      operationId: getNote
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: integer
            format: int64
      responses:
        '200':
          description: successful operation
          content:
            '*/*':
              schema:
                $ref: '#/components/schemas/ResponseNoteResponse'
        '400':
          description: failed operation
          content:
            '*/*':
              schema:
                $ref: '#/components/schemas/ResponseMessage'
        '401':
          description: failed operation
          content:
            '*/*':
              schema:
                $ref: '#/components/schemas/ResponseMessage'
      security:
        - bearerAuth: []
    post:
      tags:
        - note
      summary: Update User Note
      operationId: updateNote
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: integer
            format: int64
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/NoteRequest'
        required: true
      responses:
        '200':
          description: successful operation
          content:
            '*/*':
              schema:
                $ref: '#/components/schemas/ResponseNoteResponse'
        '400':
          description: failed operation
          content:
            '*/*':
              schema:
                $ref: '#/components/schemas/ResponseMessage'
        '401':
          description: failed operation
          content:
            '*/*':
              schema:
                $ref: '#/components/schemas/ResponseMessage'
      security:
        - bearerAuth: []
    delete:
      tags:
        - note
      summary: Delete User Note
      operationId: deleteNote
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: integer
            format: int64
      responses:
        '204':
          description: successful operation
        '400':
          description: failed operation
          content:
            '*/*':
              schema:
                $ref: '#/components/schemas/ResponseMessage'
        '401':
          description: failed operation
          content:
            '*/*':
              schema:
                $ref: '#/components/schemas/ResponseMessage'
      security:
        - bearerAuth: []
components:
  schemas:
    SignRequest:
      required:
        - email
        - password
      type: object
      properties:
        email:
          maxLength: 50
          minLength: 3
          type: string
        password:
          maxLength: 50
          minLength: 6
          type: string
    ResponseSign:
      type: object
      properties:
        message:
          type: string
        data:
          type: string
          default: token
    ResponseMessage:
      type: object
      properties:
        message:
          type: string
    NoteRequest:
      required:
        - content
      type: object
      properties:
        content:
          type: string
        isCompleted:
          type: boolean
    NoteResponse:
      type: object
      properties:
        id:
          type: integer
          format: int32
        content:
          type: string
        isCompleted:
          type: boolean
    ResponseNoteResponse:
      type: object
      properties:
        message:
          type: string
        data:
          $ref: '#/components/schemas/NoteResponse'
    ResponseListNoteResponse:
      type: object
      properties:
        message:
          type: string
        data:
          type: array
          items:
            $ref: '#/components/schemas/NoteResponse'
  securitySchemes:
    bearerAuth:
      type: http
      scheme: bearer
      bearerFormat: JWT
