spring:
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
  datasource:
    url: jdbc:mysql://${MYSQL_HOST:mysqldb}:3306/${MYSQL_DATABASE:db_example}
    username: ${MYSQL_USERNAME:root}
    password: ${MYSQL_PASSWORD:root}
    driver-class-name: com.mysql.cj.jdbc.Driver
    validationQuery: SELECT 1

server:
  port: ${SERVER_PORT:8080}